eureka:
  client:
    register-with-eureka: true  #Need to register with eureka
    fetch-registry: true #Have to fetch microservices details from registry
    service-url:
      defaultZone: http://localhost:8761/eureka/ #eureka server url
  instance:
    hostname: localhost    #If in production or other environment, give the hostname of that env
